# Generated by Django 4.2.1 on 2023-05-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wiki_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catinfo',
            name='cat_img05',
        ),
        migrations.RemoveField(
            model_name='catinfo',
            name='cat_img06',
        ),
        migrations.RemoveField(
            model_name='catinfo',
            name='cat_img07',
        ),
        migrations.RemoveField(
            model_name='catinfo',
            name='cat_img08',
        ),
    ]
