# Generated by Django 4.2.1 on 2023-05-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_wiki_api', '0004_alter_teste_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='teste_img'),
        ),
    ]
